apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume-claim
spec:
  storageClassName: local-storage
  accessModes: 
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi

